services:
  # Aplicação Spring Boot
  - type: web
    name: smart-mesquita-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: smart-mesquita-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://nawatfrontend-btrc1qyvc-alvaro-mashnis-projects.vercel.app/
      - key: REDIS_HOST
        fromService:
          name: smart-mesquita-redis
          type: keyvalue
          property: host
      - key: REDIS_PORT
        fromService:
          name: smart-mesquita-redis
          type: keyvalue
          property: port
      - key: REDIS_PASSWORD
        fromService:
          name: smart-mesquita-redis
          type: keyvalue
          property: password
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
    healthCheckPath: /actuator/health

  # Redis (para rate limiting e sessions)
  - type: keyvalue
    name: smart-mesquita-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

# Banco de dados PostgreSQL
databases:
  - name: smart-mesquita-db
    databaseName: smartmesquita
    user: smartmesquita
    plan: free
    ipAllowList: []
